### ISSUE TITLE
feat: 유저 인증/인가 기능 개발

### ISSUE THREAD

**Issue by Hwan0518** [ApptiveDev/ygyg-be#6]
## Description
- 로그인/회원가입에서 사용되는 인증/인가 기능들을 개발한다
- 스프링 security를 설정한다

## To-Do

- [x] 유저 entity, 서비스 알게된 경로 entity 생성 및 db 연결
- [x] 이메일 중복 확인 API 개발
- [x] 인증 이메일 전송 API 개발
- [x] 인증번호 확인 API 개발
- [x] 닉네임 중복확인 API 개발
- [x] security 설정
- [x] jwt 설정
- [x] 회원가입 API 개발
- [x] 로그인 API 개발

## ETC
- x
